// One-time seed data for the Firestore "events" collection.
// Used only by seed/seed.js and seed/reseed.js — the live app reads from Firestore afterwards.
//
// Schema per event:
//   section: "Morning" | "Solemnisation" | "Dinner"   — coarse nav grouping
//   side:    "bride" | "groom" | "everyone"            — which lane on the desktop timeline
//   start/end: "HH:MM" (24h)
//   title, location
//   poc: string[]        — people/vendors responsible (empty = generic, relevant to everyone)
//   deadline: string|null — a critical-path cutoff worth surfacing prominently
//   tasks: string[]       — prep notes / assigned tasks, shown when expanded
module.exports = [
  // ---------------- Morning ----------------
  { section: "Morning", side: "bride", start: "05:00", end: "05:30",
    title: "Bride wakes up & light breakfast", location: "Bride's Home",
    poc: [], deadline: null,
    tasks: [
      "Light breakfast before makeup starts.",
      "Prepare ROM required documents and tea set for the tea ceremony.",
      "Prepare breakfast and personal items.",
    ] },
  { section: "Morning", side: "bride", start: "05:30", end: "08:00",
    title: "Bride hair & makeup", location: "Bride's Home",
    poc: ["Imelda"], deadline: null,
    tasks: ["Makeup artist (Imelda) arrives and starts bride hair and makeup."] },
  { section: "Morning", side: "bride", start: "07:00", end: "08:00",
    title: "Photographer & bridesmaids arrive", location: "Bride's Home",
    poc: [], deadline: null,
    tasks: [
      "Photographer/videographer and bridesmaids arrive.",
      "Bridesmaids prepare gatecrash logistics.",
      "Discuss wedding flow with photographer.",
    ] },
  { section: "Morning", side: "groom", start: "07:00", end: "08:00",
    title: "Groom wakes up, entourage gathers", location: "Groom's Home",
    poc: [], deadline: "Leave by 7:50 AM",
    tasks: [
      "Groom wakes up.",
      "Photographer/videographer and groomsmen gather.",
      "Groom prepares angbaos.",
      "Prepare the bouquet of wedding flowers.",
    ] },
  { section: "Morning", side: "everyone", start: "08:30", end: "10:10",
    title: "Gatecrash & bride-side tea ceremony", location: "Bride's Home",
    poc: [], deadline: null,
    tasks: [
      "Bride dressed; photos with parents and bridesmaids.",
      "Gatecrash activities (30–40 mins).",
      "Groom arrives at bride's house.",
      "Bride-side tea ceremony — bai bai + tea ceremony (45 mins).",
    ] },
  { section: "Morning", side: "everyone", start: "10:20", end: "11:00",
    title: "Travel to groom's house", location: "En route to Groom's Home",
    poc: [], deadline: null,
    tasks: ["Couple travels to groom's house.", "Bridesmaids help fetch bride's ROM documents, evening gown and shoes."] },
  { section: "Morning", side: "everyone", start: "11:00", end: "12:45",
    title: "Tea ceremony at groom's house", location: "Groom's Home",
    poc: [], deadline: null,
    tasks: [
      "Couple reaches groom's house and serves tea to groom's family.",
      "Bring ring pillow, laptop/thumbdrive, ROM documents and ICs.",
      "Confirm transport logistics: how many cars are coming from the groom's side?",
    ] },
  { section: "Morning", side: "everyone", start: "12:45", end: "14:00",
    title: "Lunch break & rest", location: "Groom's Home",
    poc: [], deadline: null,
    tasks: ["Lunch break and rest before evening preparation."] },

  // ---------------- Solemnisation ----------------
  { section: "Solemnisation", side: "everyone", start: "14:00", end: "17:00",
    title: "Evening makeup at Fullerton bridal suite", location: "Fullerton Hotel — Bridal Suite",
    poc: ["Shuyin", "Imelda"], deadline: null,
    tasks: [
      "Bride and groom evening makeup.",
      "Ensure evening gowns, shoes and accessories are brought to the bridal room.",
      "Imelda (MUA) to arrive beforehand and meet in the bridal room.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "16:00", end: "17:30",
    title: "Ballroom & reception deco setup", location: "Fullerton Hotel — Ballroom & Reception",
    poc: ["Xinli", "MingFeng", "Victoria Wedding"], deadline: null,
    tasks: [
      "Victoria Wedding arrives and sets up ballroom and reception deco.",
      "Ballroom deco: staircase, white carpet, floral aisle.",
      "Reception area deco: photo gallery.",
      "Pending theme & photos to be shared with them.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "16:30", end: "17:00",
    title: "Reception & registration table setup", location: "Fullerton Hotel — Reception Area",
    poc: ["Weiqing", "Jieyi", "Wu Yueze", "Tan Jun Hong"], deadline: null,
    tasks: [
      "Reception gallery table deco set up inside the reception hall.",
      "Registration table for 4 pax set up outside the reception hall, register via laptop.",
      "Physical floor plan and angbao box will be provided.",
      "Coordinate with banquet manager on last-minute seating changes.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "16:30", end: "17:00",
    title: "Handover briefing & AV run-through", location: "Fullerton Hotel — Ballroom",
    poc: ["Yao", "Junle", "Clarence", "Aaron", "Justine"], deadline: null,
    tasks: [
      "Briefing with banquet manager.",
      "Bring laptop and charger.",
      "Test pws, childhood and morning SDE highlight videos.",
      "Test lighting, music and microphones (2 wireless provided).",
      "Ensure the 3-tier dummy cake is set.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "17:00", end: "17:45",
    title: "Bridal party photoshoot at Fullerton", location: "Fullerton Hotel",
    poc: ["Shuyin", "Xinxuan"], deadline: null,
    tasks: [
      "Photo/videographers to arrive beforehand.",
      "Coordinate with photographers on solemnisation filming flow.",
      "Coordinate photo setups during the banquet (march-in, toasting, cake cutting).",
    ] },
  { section: "Solemnisation", side: "everyone", start: "17:15", end: "18:15",
    title: "Musical Touch band & sound crew setup", location: "Fullerton Hotel — Ballroom",
    poc: ["Junle", "Clarence", "Aaron", "Musical Touch"], deadline: null,
    tasks: [
      "2 musicians + 2 soundmen arrive and set up.",
      "Grabfood ordered for their dinner (MingFeng to arrange).",
      "Song list pending confirmation.",
      "Coordinate with technicians on when to play which videos.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "17:30", end: "18:00",
    title: "Photobooth & telebooth setup", location: "Fullerton Hotel — Reception Area",
    poc: ["Xinli", "MingFeng", "1010Media"], deadline: null,
    tasks: ["1010Media photobooth and telebooth arrive and set up.", "Share stable wireless wifi connection and socket points."] },
  { section: "Solemnisation", side: "everyone", start: "18:00", end: "19:30",
    title: "Ice cream live station setup", location: "Fullerton Hotel — Reception Area",
    poc: ["Birds of Paradise"], deadline: null,
    tasks: ["Birds of Paradise crew sets up the ice cream live station.", "Share socket points and waterpoints.", "Briefing with emcee and technicians at 6 PM."] },
  { section: "Solemnisation", side: "everyone", start: "17:45", end: "18:30",
    title: "Solemnisation ceremony & tea ceremony", location: "Fullerton Hotel — Ceremony Area",
    poc: ["Xinxuan", "Jieyi", "Mr Lee"], deadline: null,
    tasks: [
      "Solemnisation ceremony starts at 6 PM, followed by tea ceremony.",
      "Bring required documents, flower, ring and ring pillow.",
      "Liaise with Solemniser Mr Lee.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "18:30", end: "19:00",
    title: "Reception registration opens", location: "Fullerton Hotel — Reception Area",
    poc: ["Weiqing", "Jieyi", "Jingyang", "Sheryl", "Tan Jun Hong", "Wu Yueze"], deadline: null,
    tasks: [
      "Reception registration table opens 6:30 PM; cocktail/canapés start 6:45 PM.",
      "Guest registration, handing out door gifts & parking coupons.",
      "Safekeep the angbao box.",
      "Usher guests to the reception area to enjoy booths, canapés and the photo gallery.",
      "Guests write blessing notes for the lucky draw box; 5–6 winners will be randomly selected and read aloud.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "19:00", end: "19:20",
    title: "Ballroom doors open", location: "Fullerton Hotel — Ballroom",
    poc: ["Qiao Han"], deadline: null,
    tasks: [
      "Ballroom door opens for guests to enter.",
      "Confirm guest attendance and prepare for dinner to start; LED displays the pws montage/photos.",
      "Emcee announces the ballroom is open at 7:00 PM.",
      "Reception table closes ~7:15 PM; usher guests into the ballroom ~7:15 PM.",
      "Escort the angbao box to the hotel room for safekeeping.",
    ] },
  { section: "Solemnisation", side: "everyone", start: "19:20", end: "19:30",
    title: "Welcome & childhood montage → first march-in cue", location: "Fullerton Hotel — Ballroom",
    poc: ["Junle", "Clarence", "Aaron", "Justine"], deadline: null,
    tasks: [
      "Emcees welcome guests and play the childhood montage.",
      "At the end of the montage, guests stand for the couple's first march-in; couple stands by outside the ballroom.",
      "Groomsmen confirm the couple is ready before cueing the emcee.",
      "Play the march-in song once the emcee cues.",
    ] },

  // ---------------- Dinner ----------------
  { section: "Dinner", side: "everyone", start: "19:30", end: "19:40",
    title: "First march-in & cake-cutting ceremony", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", side: "everyone", start: "19:40", end: "20:00",
    title: "Course 1: starter/appetiser", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null,
    tasks: ["Music (part 1) plays 7:50–8:35 PM.", "Bride changes into her evening gown after this course."] },
  { section: "Dinner", side: "everyone", start: "20:00", end: "20:20",
    title: "Course 2: soup", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: "Lucky draw entries close 8:45 PM",
    tasks: ["Emcee reminds guests that lucky draw participation closes by 8:45 PM."] },
  { section: "Dinner", side: "everyone", start: "20:20", end: "20:40",
    title: "Course 3: main seafood course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null,
    tasks: [
      "While the band rests, background music and montage play.",
      "Groomsmen confirm the couple is ready and cue the emcee.",
      "Prep prizes and bring the lucky draw box to the emcee/stage.",
      "Bridesmaids/groomsmen prep bubbles.",
    ] },
  { section: "Dinner", side: "everyone", start: "20:40", end: "20:50",
    title: "Second march-in", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: ["Band sings/plays music for the march-in."] },
  { section: "Dinner", side: "everyone", start: "20:50", end: "21:10",
    title: "Course 4: vegetable course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: ["Timing may shift depending on how quickly the second march-in completes."] },
  { section: "Dinner", side: "everyone", start: "20:50", end: "21:10",
    title: "Thank-you speeches, lucky draw & gift presentation", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", side: "everyone", start: "21:10", end: "21:20",
    title: "Champagne toasting / yum seng", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", side: "everyone", start: "21:10", end: "21:30",
    title: "Course 5: rice/noodle course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", side: "everyone", start: "21:20", end: "21:30",
    title: "Morning highlights video shown", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", side: "everyone", start: "21:30", end: "21:50",
    title: "Course 6: dessert course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", side: "everyone", start: "21:30", end: "22:25",
    title: "Table photo taking", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null,
    tasks: [
      "Music (part 2) plays 9:30–10:15 PM.",
      "Coordinate with photographers on photo taking with guests after the 2nd march-in.",
      "~2 to 3 minutes per table.",
    ] },
  { section: "Dinner", side: "everyone", start: "22:25", end: "22:35",
    title: "Farewell & final group photos", location: "Fullerton Hotel — Ballroom",
    poc: ["Bride", "Groom", "Parents", "Photographer"], deadline: null,
    tasks: ["Bid guests farewell and take final group photos.", "Coordinate remaining family and bridal party photos."] },
  { section: "Dinner", side: "everyone", start: "22:35", end: "23:00",
    title: "Vendor teardown", location: "Fullerton Hotel — Ballroom & Reception",
    poc: [], deadline: null,
    tasks: [
      "Photobooth, Victoria Wedding deco and Musical Touch teardown.",
      "Each segment's POC ensures teardown and brings remaining items into the bridal suite, or asks the banquet manager for disposal.",
    ] },
  { section: "Dinner", side: "everyone", start: "22:45", end: "23:00",
    title: "Clear ballroom items", location: "Fullerton Hotel — Ballroom",
    poc: ["Bridesmaids & Groomsmen"], deadline: null,
    tasks: ["Clear items from the ballroom and send them to the hotel room.", "Collect reception decor, photo album, gown bags, shoes and personal items."] },
];
