// One-time seed data for the Firestore "events" collection.
// Used only by seed/seed.js and seed/reseed.js — the live app reads from Firestore afterwards.
//
// Schema per event:
//   section:  "Morning" | "Afternoon" | "Solemnisation" | "Reception" | "Dinner"
//   track:    "program" — guest-facing flow | "setup" — backstage vendor work
//   side:     "bride" | "groom" | "everyone"
//   start/end: "HH:MM" (24h)
//   title, location
//   poc:      person IDs from data.js PEOPLE — never free text, or the chip goes dead
//   deadline: string|null — a hard cutoff; the one place a time may be written in words
//   tasks:    string[] — prep notes. Deliberately contain NO times: every time that
//             matters is either start/end or a deadline, so the two can't drift apart.
//
// Anything still undecided is written as "Confirm: …" so it is searchable and
// obvious on the card rather than being silently assumed.
module.exports = [
  // ============================ MORNING ============================
  { section: "Morning", track: "program", side: "bride", start: "05:00", end: "05:30",
    title: "Bride wakes up & light breakfast", location: "Bride's Home",
    poc: ["bride"], deadline: null,
    tasks: [
      "Eat something before makeup — it is a long stretch to lunch.",
      "Lay out the ROM documents and both NRICs where they cannot be forgotten.",
      "Set out the tea set and kneeling cushions for the tea ceremony.",
      "Pack the day bag: touch-up makeup, flats, phone charger, power bank.",
    ] },
  { section: "Morning", track: "program", side: "bride", start: "05:30", end: "08:00",
    title: "Bride hair & makeup", location: "Bride's Home",
    poc: ["bride", "imelda"], deadline: null,
    tasks: [
      "Hair and makeup, finishing in time to dress before the gatecrash.",
      "Dress with help from the bridesmaids once makeup is set.",
      "Keep the gown covered until the photographer is ready for the reveal.",
    ] },
  { section: "Morning", track: "program", side: "bride", start: "07:00", end: "08:00",
    title: "Bridesmaids arrive & set up gatecrash", location: "Bride's Home",
    poc: ["shuyin", "justine", "xinxuan", "jieyi"], deadline: null,
    tasks: [
      "Set up the gatecrash games and lay out anything the groomsmen have to eat, drink or wear.",
      "Agree who films the gatecrash on a phone as a backup to the videographer.",
      "Brief the photographer on the flow and the shots that matter to the family.",
      "Set up the emergency kit: safety pins, sewing kit, plasters, painkillers, tissues, stain remover, double-sided tape.",
    ] },
  { section: "Morning", track: "setup", side: "bride", start: "07:15", end: "07:30",
    title: "Depair photo/video call time — bride's side", location: "Bride's Home",
    poc: ["pauline"], deadline: null,
    tasks: ["Photographer and videographer arrive to cover the bride's preparations."] },
  { section: "Morning", track: "program", side: "groom", start: "07:00", end: "08:00",
    title: "Groom wakes up, entourage gathers", location: "Groom's Home",
    poc: ["groom", "junle", "clarence", "aaron"], deadline: "Leave by 7:50 AM",
    tasks: [
      "Groom dresses; groomsmen gather and dress.",
      "Count out the gatecrash angbaos and keep spare small notes on hand.",
      "Collect the bridal bouquet and keep it cool and out of direct sun.",
      "Load the cars: bouquet, angbaos, ring pillow, change of shirts.",
      "Confirm: which car is the bridal car, who is driving it, and is it decorated?",
    ] },
  { section: "Morning", track: "setup", side: "groom", start: "07:30", end: "07:45",
    title: "Depair photo/video call time — groom's side", location: "Groom's Home",
    poc: ["pauline"], deadline: null,
    tasks: ["Second Depair crew arrives to cover the groom's preparations."] },
  { section: "Morning", track: "program", side: "everyone", start: "08:30", end: "10:10",
    title: "Gatecrash & bride-side tea ceremony", location: "Bride's Home",
    poc: ["shuyin", "justine", "junle", "clarence"], deadline: null,
    tasks: [
      "Bride dressed; photos with her parents and the bridesmaids.",
      "Gatecrash games, then the groom is let in to collect the bride.",
      "Bai bai, followed by the tea ceremony with the bride's family.",
      "One bridesmaid collects every angbao and any jewellery given during the tea ceremony into a single named bag.",
      "Confirm: the order of relatives to be served tea, written down for the day.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "10:20", end: "11:00",
    title: "Travel to groom's house", location: "En route to Groom's Home",
    poc: ["shuyin", "justine"], deadline: null,
    tasks: [
      "Couple travels in the bridal car; the entourage follows.",
      "Bring the bride's ROM documents, evening gown, shoes and accessories — these go on to the hotel later, so do not leave them behind.",
      "Carry the angbao and jewellery bag from the first tea ceremony.",
      "Do a final sweep of the bride's room before leaving.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "11:00", end: "12:45",
    title: "Tea ceremony at groom's house", location: "Groom's Home",
    poc: ["junle", "clarence", "parents"], deadline: null,
    tasks: [
      "Couple serves tea to the groom's family.",
      "Bring in the ring pillow, laptop and thumbdrive, ROM documents and both NRICs.",
      "Second collection of angbaos and jewellery — add them to the same named bag, one person responsible for it all day.",
      "Confirm: how many cars are coming from the groom's side, and who rides in which.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "12:45", end: "14:00",
    title: "Lunch break & rest", location: "Groom's Home",
    poc: [], deadline: "Leave for the hotel by 1:30 PM",
    tasks: [
      "Eat properly — this is the last real meal before the banquet for most of the bridal party.",
      "Change out of the morning outfits and repack for the hotel.",
      "Charge phones and power banks before leaving.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "13:30", end: "14:00",
    title: "Travel to Fullerton Hotel", location: "En route to Fullerton Hotel",
    poc: ["shuyin", "junle"], deadline: null,
    tasks: [
      "Couple and bridal party travel to the hotel.",
      "Load everything for the evening: gowns, suits, shoes, accessories, ROM documents, ring pillow, laptop and charger, thumbdrive, angbao and jewellery bag, emergency kit.",
      "Collect the bridal suite key on arrival and take everything straight up.",
      "Confirm: hotel check-in time, and whether the suite is available before the makeup slot.",
    ] },

  // =========================== AFTERNOON ===========================
  { section: "Afternoon", track: "program", side: "everyone", start: "14:00", end: "17:00",
    title: "Evening makeup at Fullerton bridal suite", location: "Fullerton Hotel — Bridal Suite",
    poc: ["bride", "groom", "shuyin", "imelda"], deadline: null,
    tasks: [
      "Bride and groom evening hair and makeup.",
      "Hang the evening gowns to drop any creases as soon as you reach the room.",
      "Lay out shoes, accessories and jewellery ready for the photoshoot.",
      "Keep the emergency kit and a steamer in the suite — this room is the base for the rest of the night.",
      "Eat something light; there is no other break before the banquet.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:00", end: "17:30",
    title: "Ballroom & reception deco setup", location: "Fullerton Hotel — Ballroom & Reception",
    poc: ["xinli", "mingfeng", "scarlet", "shawn"], deadline: "Deco complete by 5:45 PM",
    tasks: [
      "Victoria Wedding sets up the ballroom and reception deco.",
      "Ballroom: staircase, white carpet, floral aisle.",
      "Reception area: photo gallery.",
      "Walk the room once setup is called done and photograph it — that is your record if anything is wrong later.",
      "Confirm: the deco theme and photo selection have been sent to Victoria Wedding.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:00", end: "17:00",
    title: "Floral table setup", location: "Fullerton Hotel — Ceremony Area",
    poc: ["xinxuan", "priscilla"], deadline: "Floral table done by 5:30 PM",
    tasks: [
      "Mirage Florist sets the solemnisation floral table.",
      "Check the table against the agreed design before the florist leaves.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:30", end: "17:00",
    title: "Reception & registration table setup", location: "Fullerton Hotel — Reception Area",
    poc: ["weiqing", "jieyi", "chiaqing", "yueze", "junhong"], deadline: null,
    tasks: [
      "Set up the reception gallery table inside the reception hall.",
      "Set up the registration table for four outside the reception hall, with both laptops on the guest list.",
      "Lay out the floor plan, door gifts, parking coupons, wishing cards and the lucky draw box.",
      "Set out both angbao boxes and agree who is responsible for each.",
      "Check both laptops can search the guest list quickly, and keep a printed list as backup.",
      "Take the banquet manager's number and confirm who to call about seating changes.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:30", end: "17:00",
    title: "Handover briefing & AV run-through", location: "Fullerton Hotel — Ballroom",
    poc: ["yaoleyang", "junle", "clarence", "aaron", "justine", "zahera"], deadline: null,
    tasks: [
      "Briefing with the banquet manager on the full running order.",
      "Bring the laptop, its charger and the backup thumbdrive.",
      "Play the pws montage, childhood montage and morning highlights video end to end — check the sound level on each.",
      "Test the lighting, music and both wireless microphones.",
      "Check the 3.5mm audio jack works with the laptop and keep an adapter on hand.",
      "Confirm the 3-tier dummy cake is in place and the cutting knife is ready.",
      "Agree the exact cue for each video and who gives it.",
    ] },
  { section: "Afternoon", track: "program", side: "everyone", start: "17:00", end: "17:45",
    title: "Bridal party photoshoot at Fullerton", location: "Fullerton Hotel",
    poc: ["shuyin", "xinxuan", "yaoleyang", "pauline"], deadline: null,
    tasks: [
      "Couple, bridal party and immediate family photos.",
      "Work from a written list of family groupings so nobody is missed or left waiting.",
      "Agree the solemnisation filming positions with the photographers.",
      "Agree the banquet photo setups now: both march-ins, toasting, cake cutting, table photos.",
      "Confirm: which family members must be in the formal photos, and are they all on site by now.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "17:15", end: "18:15",
    title: "Musical Touch band & sound setup", location: "Fullerton Hotel — Ballroom",
    poc: ["junle", "clarence", "julian"], deadline: null,
    tasks: [
      "Two musicians and two soundmen arrive and set up.",
      "Agree with the technicians which video plays at which cue.",
      "Confirm: the song list, including the march-in songs for both entrances.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "17:30", end: "18:00",
    title: "Photobooth & telebooth setup", location: "Fullerton Hotel — Reception Area",
    poc: ["xinli", "mingfeng", "ryanjee", "alistair"], deadline: null,
    tasks: [
      "1010Media photobooth and telebooth arrive and set up.",
      "Give them the wifi password and show them the socket points.",
      "Test one print end to end before guests arrive.",
    ] },

  // ========================= SOLEMNISATION =========================
  { section: "Solemnisation", track: "setup", side: "everyone", start: "17:45", end: "18:00",
    title: "Solemniser arrives & final ceremony check", location: "Fullerton Hotel — Ceremony Area",
    poc: ["xinxuan", "jieyi", "aaron", "mrlee"], deadline: null,
    tasks: [
      "Walk the solemniser through the order of proceedings and where everyone stands.",
      "Both witnesses present with their NRICs — the ROM cannot proceed without them.",
      "Lay out the ROM documents, both NRICs, the rings and the ring pillow.",
      "Cue up the march-in music and test the 3.5mm audio jack one final time.",
      "Confirm: who the two witnesses are, and that both know they are needed at this point.",
    ] },
  { section: "Solemnisation", track: "program", side: "everyone", start: "18:00", end: "18:20",
    title: "Solemnisation ceremony", location: "Fullerton Hotel — Ceremony Area",
    poc: ["bride", "groom", "mrlee"], deadline: null,
    tasks: [
      "Solemnisation conducted by Mr Lee, with both witnesses signing.",
      "Exchange of rings.",
      "Collect the signed marriage certificate straight afterwards and put it somewhere safe — do not leave it on the table.",
    ] },
  { section: "Solemnisation", track: "program", side: "everyone", start: "18:20", end: "18:30",
    title: "Tea ceremony", location: "Fullerton Hotel — Ceremony Area",
    poc: ["bride", "groom", "parents", "xinxuan", "jieyi"], deadline: null,
    tasks: [
      "Tea ceremony with both families immediately after the solemnisation.",
      "Collect any angbaos or jewellery given here into the same named bag.",
      "Clear the ceremony area afterwards so guests can move through.",
    ] },
  { section: "Solemnisation", track: "setup", side: "everyone", start: "18:00", end: "18:30",
    title: "Vendor briefing & crew dinner", location: "Fullerton Hotel — Reception Area",
    poc: ["xinli", "mingfeng", "qiaohan"], deadline: null,
    tasks: [
      "Run the full program flow with the emcee and technicians, cue by cue.",
      "Give the emcee the name pronunciations and the correct order of thank-yous.",
      "Grabfood for the band and crew dinner — MingFeng to arrange.",
      "Confirm: red packets for the vendors, who hands them over and when.",
    ] },
  { section: "Solemnisation", track: "setup", side: "everyone", start: "18:00", end: "19:30",
    title: "Ice cream live station setup", location: "Fullerton Hotel — Reception Area",
    poc: ["yuntong", "birds"], deadline: null,
    tasks: [
      "Birds of Paradise set up the ice cream live station.",
      "Show them the socket and water points.",
    ] },

  // ============================ RECEPTION ==========================
  { section: "Reception", track: "program", side: "everyone", start: "18:30", end: "19:00",
    title: "Reception registration opens", location: "Fullerton Hotel — Reception Area",
    poc: ["weiqing", "jieyi", "jingyang", "sheryl", "junhong", "yueze"], deadline: "Registration table open by 6:30 PM",
    tasks: [
      "Register guests, hand out door gifts and parking coupons.",
      "Cocktails and canapés served in the reception area.",
      "Angbaos go straight into the boxes; never leave a box unattended.",
      "Usher guests towards the booths, canapés and photo gallery.",
      "Point guests to the lucky draw box and explain the blessing notes.",
      "Keep a running note of no-shows and walk-ins for the banquet manager.",
    ] },
  { section: "Reception", track: "program", side: "everyone", start: "19:00", end: "19:20",
    title: "Ballroom doors open", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan", "weiqing", "junhong"], deadline: "Reception table closes 7:15 PM",
    tasks: [
      "Emcee announces that the ballroom is open.",
      "LED displays the pws montage as guests come in.",
      "Usher guests in and help anyone who cannot find their table.",
      "Give the banquet manager the final headcount.",
      "Escort both angbao boxes to the hotel room and lock them away — two people, together.",
    ] },
  { section: "Reception", track: "program", side: "everyone", start: "19:20", end: "19:30",
    title: "Welcome & childhood montage", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan", "junle", "clarence", "aaron", "justine"], deadline: null,
    tasks: [
      "Emcees welcome the guests and play the childhood montage.",
      "Couple stands by outside the ballroom during the montage.",
      "Groomsmen confirm the couple is ready before cueing the emcee.",
      "Guests are asked to stand as the montage ends; play the march-in song on the cue.",
    ] },

  // ============================= DINNER ============================
  { section: "Dinner", track: "program", side: "everyone", start: "19:30", end: "19:40",
    title: "First march-in & cake-cutting ceremony", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "pauline"], deadline: null,
    tasks: [
      "Couple marches in, followed by the cake cutting.",
      "Hold the pose at the cake for the photographers before cutting.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "19:40", end: "20:00",
    title: "Course 1: starter/appetiser", location: "Fullerton Hotel — Ballroom",
    poc: ["justine"], deadline: null,
    tasks: [
      "Make sure the bridal party's table is served — they eat in shifts around their duties.",
      "Check the tables with dietary requirements are served correctly: halal, kid menus, no beef, no crustaceans, no vegetables.",
    ] },
  { section: "Dinner", track: "setup", side: "everyone", start: "19:50", end: "20:35",
    title: "Band set 1", location: "Fullerton Hotel — Ballroom",
    poc: ["julian"], deadline: null,
    tasks: ["Musical Touch performs the first live set."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:00", end: "20:20",
    title: "Course 2: soup", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan"], deadline: null,
    tasks: ["Emcee reminds guests that lucky draw participation is closing soon."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:00", end: "20:20",
    title: "Bride's gown change", location: "Fullerton Hotel — Bridal Suite",
    poc: ["bride", "shuyin", "imelda"], deadline: null,
    tasks: [
      "Bride changes into the evening gown and touches up hair and makeup.",
      "Take the room key — do not get locked out mid-change.",
      "Bring the emergency kit; this is when a hem or a strap usually needs fixing.",
      "Confirm: is the makeup artist staying through the gown change, or does the bride change with the bridesmaids only?",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:20", end: "20:40",
    title: "Course 3: main seafood course", location: "Fullerton Hotel — Ballroom",
    poc: ["junle", "clarence", "justine"], deadline: null,
    tasks: [
      "Background music and montage play while the band rests.",
      "Groomsmen confirm the couple is ready and cue the emcee.",
      "Bring the prizes and the lucky draw box to the emcee at the stage.",
      "Bridesmaids and groomsmen prepare the bubbles along the march-in route.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:40", end: "20:50",
    title: "Second march-in", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "julian"], deadline: "Lucky draw entries close 8:45 PM",
    tasks: ["Band plays the couple in for the second march-in."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:50", end: "21:10",
    title: "Thank-you speeches, lucky draw & gift presentation", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan", "bride", "groom"], deadline: null,
    tasks: [
      "Thank-you speeches.",
      "Five to six lucky draw winners drawn at random and read aloud.",
      "Have the prizes ready at the stage and someone to hand them over.",
      "Confirm: who speaks, in what order, and for roughly how long.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:50", end: "21:10",
    title: "Course 4: vegetable course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null,
    tasks: ["Timing may shift depending on how quickly the second march-in completes."] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:10", end: "21:20",
    title: "Champagne toasting / yum seng", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "parents"], deadline: null,
    tasks: [
      "Champagne tower and toast, followed by yum seng.",
      "Agree beforehand who leads the yum seng and how many rounds.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:10", end: "21:30",
    title: "Course 5: rice/noodle course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:20", end: "21:30",
    title: "Morning highlights video shown", location: "Fullerton Hotel — Ballroom",
    poc: ["yaoleyang", "junhong"], deadline: null,
    tasks: ["Play the same-day edit of the morning; check the sound level before it starts."] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:30", end: "21:50",
    title: "Course 6: dessert course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", track: "setup", side: "everyone", start: "21:30", end: "22:15",
    title: "Band set 2", location: "Fullerton Hotel — Ballroom",
    poc: ["julian"], deadline: null,
    tasks: ["Musical Touch performs the second live set."] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:30", end: "22:25",
    title: "Table photo taking", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "pauline"], deadline: null,
    tasks: [
      "Couple visits each table for a photo, roughly two to three minutes per table.",
      "A bridesmaid or groomsman walks one table ahead to get the next table standing and ready.",
      "Start with the VIP table and the tables with elderly guests, who tend to leave earliest.",
      "Someone carries water for the couple — this is twenty straight tables.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "22:25", end: "22:35",
    title: "Farewell & final group photos", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "parents", "pauline"], deadline: null,
    tasks: [
      "Couple and both sets of parents see guests out at the ballroom doors.",
      "Hand out any remaining door gifts as guests leave.",
      "Final family and bridal party group photos once the room has cleared.",
    ] },
  { section: "Dinner", track: "setup", side: "everyone", start: "22:35", end: "23:00",
    title: "Vendor teardown", location: "Fullerton Hotel — Ballroom & Reception",
    poc: ["xinli", "mingfeng", "ryanjee", "yuntong", "alistair", "scarlet", "julian"], deadline: null,
    tasks: [
      "Photobooth, Victoria Wedding deco and Musical Touch teardown.",
      "Each segment's POC confirms their vendor is done and nothing of ours has been packed away by mistake.",
      "Collect the photobooth prints and the guest book.",
      "Hand over the vendor red packets.",
    ] },
  { section: "Dinner", track: "setup", side: "everyone", start: "22:45", end: "23:00",
    title: "Clear ballroom items", location: "Fullerton Hotel — Ballroom",
    poc: ["bmgm"], deadline: null,
    tasks: [
      "Clear everything of ours from the ballroom and reception up to the hotel room.",
      "Collect the reception decor, photo album, gown bags, shoes and personal items.",
      "Account for the angbao boxes, the jewellery bag and the signed marriage certificate before anyone leaves.",
      "Final sweep of the bridal suite, ballroom and reception area.",
    ] },
];
