// One-time seed data for the Firestore "events" collection.
// Used only by seed/seed.js and seed/reseed.js — the live app reads from Firestore afterwards.
//
// Schema per event:
//   section:  "Morning" | "Afternoon" | "Solemnisation" | "Reception" | "Dinner"
//             — derived from where the event actually falls in the day, not hand-labelled
//   track:    "program" — guest-facing flow, what the day looks like from a seat
//             "setup"   — backstage: vendor calls, builds, briefings, teardown
//   side:     "bride" | "groom" | "everyone"
//   start/end: "HH:MM" (24h)
//   title, location
//   poc:      person IDs from data.js PEOPLE — never free text, or the chip goes dead
//   deadline: string|null — a hard cutoff; the one place a time may be written in words
//   tasks:    string[] — prep notes. Deliberately contain NO times: every time that
//             matters is either start/end or a deadline, so the two can't drift apart.
module.exports = [
  // ============================ MORNING ============================
  { section: "Morning", track: "program", side: "bride", start: "05:00", end: "05:30",
    title: "Bride wakes up & light breakfast", location: "Bride's Home",
    poc: ["bride"], deadline: null,
    tasks: [
      "Light breakfast before makeup starts.",
      "Prepare ROM required documents and tea set for the tea ceremony.",
      "Prepare breakfast and personal items.",
    ] },
  { section: "Morning", track: "program", side: "bride", start: "05:30", end: "08:00",
    title: "Bride hair & makeup", location: "Bride's Home",
    poc: ["bride", "imelda"], deadline: null,
    tasks: ["Hair and makeup for the bride, allowing time to dress before the gatecrash."] },
  { section: "Morning", track: "program", side: "bride", start: "07:00", end: "08:00",
    title: "Bridesmaids arrive & prep gatecrash", location: "Bride's Home",
    poc: ["shuyin", "justine", "xinxuan", "jieyi"], deadline: null,
    tasks: [
      "Bridesmaids arrive and set up the gatecrash games.",
      "Discuss the wedding flow with the photographer.",
    ] },
  { section: "Morning", track: "setup", side: "bride", start: "07:15", end: "07:30",
    title: "Depair photo/video call time — bride's side", location: "Bride's Home",
    poc: ["pauline"], deadline: null,
    tasks: ["Photographer and videographer arrive to cover the bride's preparations."] },
  { section: "Morning", track: "program", side: "groom", start: "07:00", end: "08:00",
    title: "Groom wakes up, entourage gathers", location: "Groom's Home",
    poc: ["groom", "junle", "clarence", "aaron"], deadline: "Leave by 7:50 AM",
    tasks: [
      "Groom wakes and dresses.",
      "Groomsmen gather.",
      "Groom prepares angbaos.",
      "Prepare the bouquet of wedding flowers.",
    ] },
  { section: "Morning", track: "setup", side: "groom", start: "07:30", end: "07:45",
    title: "Depair photo/video call time — groom's side", location: "Groom's Home",
    poc: ["pauline"], deadline: null,
    tasks: ["Second Depair crew arrives to cover the groom's preparations."] },
  { section: "Morning", track: "program", side: "everyone", start: "08:30", end: "10:10",
    title: "Gatecrash & bride-side tea ceremony", location: "Bride's Home",
    poc: ["shuyin", "justine", "junle", "clarence"], deadline: null,
    tasks: [
      "Bride dressed; photos with parents and bridesmaids.",
      "Gatecrash activities.",
      "Groom arrives at the bride's house.",
      "Bride-side tea ceremony — bai bai followed by the tea ceremony.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "10:20", end: "11:00",
    title: "Travel to groom's house", location: "En route to Groom's Home",
    poc: ["shuyin", "justine"], deadline: null,
    tasks: [
      "Couple travels to the groom's house.",
      "Bridesmaids fetch the bride's ROM documents, evening gown and shoes.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "11:00", end: "12:45",
    title: "Tea ceremony at groom's house", location: "Groom's Home",
    poc: ["junle", "clarence", "parents"], deadline: null,
    tasks: [
      "Couple reaches the groom's house and serves tea to the groom's family.",
      "Bring the ring pillow, laptop/thumbdrive, ROM documents and ICs.",
      "Confirm transport logistics — how many cars are coming from the groom's side.",
    ] },
  { section: "Morning", track: "program", side: "everyone", start: "12:45", end: "14:00",
    title: "Lunch break & rest", location: "Groom's Home",
    poc: [], deadline: null,
    tasks: ["Lunch break and rest before evening preparation."] },

  // =========================== AFTERNOON ===========================
  { section: "Afternoon", track: "program", side: "everyone", start: "14:00", end: "17:00",
    title: "Evening makeup at Fullerton bridal suite", location: "Fullerton Hotel — Bridal Suite",
    poc: ["bride", "groom", "shuyin", "imelda"], deadline: null,
    tasks: [
      "Bride and groom evening makeup.",
      "Ensure evening gowns, shoes and accessories are brought to the bridal room.",
      "Makeup artist to arrive beforehand and meet in the bridal room.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:00", end: "17:30",
    title: "Ballroom & reception deco setup", location: "Fullerton Hotel — Ballroom & Reception",
    poc: ["xinli", "mingfeng", "scarlet", "shawn"], deadline: "Deco complete by 5:45 PM",
    tasks: [
      "Victoria Wedding sets up the ballroom and reception deco.",
      "Ballroom deco: staircase, white carpet, floral aisle.",
      "Reception area deco: photo gallery.",
      "Pending theme and photos to be shared with them.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:00", end: "17:00",
    title: "Floral table setup", location: "Fullerton Hotel — Ceremony Area",
    poc: ["xinxuan", "priscilla"], deadline: "Floral table done by 5:30 PM",
    tasks: ["Mirage Florist sets the solemnisation floral table."] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:30", end: "17:00",
    title: "Reception & registration table setup", location: "Fullerton Hotel — Reception Area",
    poc: ["weiqing", "jieyi", "chiaqing", "yueze", "junhong"], deadline: null,
    tasks: [
      "Reception gallery table deco set up inside the reception hall.",
      "Registration table for 4 pax set up outside the reception hall, registering via laptop.",
      "Physical floor plan and angbao box will be provided.",
      "Coordinate with the banquet manager on last-minute seating changes.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "16:30", end: "17:00",
    title: "Handover briefing & AV run-through", location: "Fullerton Hotel — Ballroom",
    poc: ["yaoleyang", "junle", "clarence", "aaron", "justine", "zahera"], deadline: null,
    tasks: [
      "Briefing with the banquet manager.",
      "Bring the laptop and charger.",
      "Test the pws, childhood and morning SDE highlight videos.",
      "Test lighting, music and microphones — two wireless mics provided.",
      "Ensure the 3-tier dummy cake is set.",
    ] },
  { section: "Afternoon", track: "program", side: "everyone", start: "17:00", end: "17:45",
    title: "Bridal party photoshoot at Fullerton", location: "Fullerton Hotel",
    poc: ["shuyin", "xinxuan", "yaoleyang", "pauline"], deadline: null,
    tasks: [
      "Photographers and videographers to arrive beforehand.",
      "Coordinate with photographers on the solemnisation filming flow.",
      "Coordinate photo setups during the banquet — march-in, toasting, cake cutting.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "17:15", end: "18:15",
    title: "Musical Touch band & sound setup", location: "Fullerton Hotel — Ballroom",
    poc: ["junle", "clarence", "julian"], deadline: null,
    tasks: [
      "Two musicians and two soundmen arrive and set up.",
      "Song list pending confirmation.",
      "Coordinate with technicians on when to play which videos.",
    ] },
  { section: "Afternoon", track: "setup", side: "everyone", start: "17:30", end: "18:00",
    title: "Photobooth & telebooth setup", location: "Fullerton Hotel — Reception Area",
    poc: ["xinli", "mingfeng", "ryanjee", "alistair"], deadline: null,
    tasks: [
      "1010Media photobooth and telebooth arrive and set up.",
      "Share a stable wifi connection and socket points.",
    ] },

  // ========================= SOLEMNISATION =========================
  { section: "Solemnisation", track: "setup", side: "everyone", start: "17:45", end: "18:00",
    title: "Solemniser arrives & final ceremony check", location: "Fullerton Hotel — Ceremony Area",
    poc: ["xinxuan", "jieyi", "aaron", "mrlee"], deadline: null,
    tasks: [
      "Liaise with the solemniser on the order of proceedings.",
      "Confirm the documents, flower, ring and ring pillow are in place.",
      "Cue the march-in music — 3.5mm audio jack.",
    ] },
  { section: "Solemnisation", track: "program", side: "everyone", start: "18:00", end: "18:20",
    title: "Solemnisation ceremony", location: "Fullerton Hotel — Ceremony Area",
    poc: ["bride", "groom", "mrlee"], deadline: null,
    tasks: ["Solemnisation ceremony conducted by the solemniser, with the couple's witnesses."] },
  { section: "Solemnisation", track: "program", side: "everyone", start: "18:20", end: "18:30",
    title: "Tea ceremony", location: "Fullerton Hotel — Ceremony Area",
    poc: ["bride", "groom", "parents", "xinxuan", "jieyi"], deadline: null,
    tasks: ["Tea ceremony immediately following the solemnisation."] },
  { section: "Solemnisation", track: "setup", side: "everyone", start: "18:00", end: "18:30",
    title: "Vendor briefing & crew dinner", location: "Fullerton Hotel — Reception Area",
    poc: ["xinli", "mingfeng", "qiaohan"], deadline: null,
    tasks: [
      "Briefing with the emcee and technicians on the full program flow.",
      "Grabfood ordered for the band and crew dinner — MingFeng to arrange.",
    ] },
  { section: "Solemnisation", track: "setup", side: "everyone", start: "18:00", end: "19:30",
    title: "Ice cream live station setup", location: "Fullerton Hotel — Reception Area",
    poc: ["yuntong", "birds"], deadline: null,
    tasks: [
      "Birds of Paradise crew sets up the ice cream live station.",
      "Share socket points and water points.",
    ] },

  // ============================ RECEPTION ==========================
  { section: "Reception", track: "program", side: "everyone", start: "18:30", end: "19:00",
    title: "Reception registration opens", location: "Fullerton Hotel — Reception Area",
    poc: ["weiqing", "jieyi", "jingyang", "sheryl", "junhong", "yueze"], deadline: "Registration table open by 6:30 PM",
    tasks: [
      "Guest registration, handing out door gifts and parking coupons.",
      "Cocktails and canapés served in the reception area.",
      "Safekeep the angbao box.",
      "Usher guests to the reception area to enjoy the booths, canapés and photo gallery.",
      "Guests write blessing notes for the lucky draw box.",
    ] },
  { section: "Reception", track: "program", side: "everyone", start: "19:00", end: "19:20",
    title: "Ballroom doors open", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan", "weiqing", "junhong"], deadline: "Reception table closes 7:15 PM",
    tasks: [
      "Emcee announces that the ballroom is open.",
      "Confirm guest attendance and prepare for dinner to start; LED displays the pws montage.",
      "Usher guests into the ballroom.",
      "Escort the angbao box to the hotel room for safekeeping.",
    ] },
  { section: "Reception", track: "program", side: "everyone", start: "19:20", end: "19:30",
    title: "Welcome & childhood montage", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan", "junle", "clarence", "aaron", "justine"], deadline: null,
    tasks: [
      "Emcees welcome the guests and play the childhood montage.",
      "At the end of the montage guests stand for the couple's first march-in; the couple stands by outside the ballroom.",
      "Groomsmen confirm the couple is ready before cueing the emcee.",
      "Play the march-in song once the emcee cues.",
    ] },

  // ============================= DINNER ============================
  { section: "Dinner", track: "program", side: "everyone", start: "19:30", end: "19:40",
    title: "First march-in & cake-cutting ceremony", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "pauline"], deadline: null, tasks: [] },
  { section: "Dinner", track: "program", side: "everyone", start: "19:40", end: "20:00",
    title: "Course 1: starter/appetiser", location: "Fullerton Hotel — Ballroom",
    poc: ["shuyin"], deadline: null,
    tasks: ["Bride changes into her evening gown after this course."] },
  { section: "Dinner", track: "setup", side: "everyone", start: "19:50", end: "20:35",
    title: "Band set 1", location: "Fullerton Hotel — Ballroom",
    poc: ["julian"], deadline: null,
    tasks: ["Musical Touch performs the first live set."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:00", end: "20:20",
    title: "Course 2: soup", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan"], deadline: null,
    tasks: ["Emcee reminds guests that lucky draw participation is closing soon."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:20", end: "20:40",
    title: "Course 3: main seafood course", location: "Fullerton Hotel — Ballroom",
    poc: ["junle", "clarence", "justine"], deadline: null,
    tasks: [
      "While the band rests, background music and the montage play.",
      "Groomsmen confirm the couple is ready and cue the emcee.",
      "Prep the prizes and bring the lucky draw box to the emcee/stage.",
      "Bridesmaids and groomsmen prep the bubbles.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:40", end: "20:50",
    title: "Second march-in", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "julian"], deadline: "Lucky draw entries close 8:45 PM",
    tasks: ["Band sings and plays music for the march-in."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:50", end: "21:10",
    title: "Thank-you speeches, lucky draw & gift presentation", location: "Fullerton Hotel — Ballroom",
    poc: ["qiaohan", "bride", "groom"], deadline: null,
    tasks: ["Five to six lucky draw winners are randomly selected and read aloud."] },
  { section: "Dinner", track: "program", side: "everyone", start: "20:50", end: "21:10",
    title: "Course 4: vegetable course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null,
    tasks: ["Timing may shift depending on how quickly the second march-in completes."] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:10", end: "21:20",
    title: "Champagne toasting / yum seng", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "parents"], deadline: null, tasks: [] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:10", end: "21:30",
    title: "Course 5: rice/noodle course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:20", end: "21:30",
    title: "Morning highlights video shown", location: "Fullerton Hotel — Ballroom",
    poc: ["yaoleyang", "junhong"], deadline: null, tasks: [] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:30", end: "21:50",
    title: "Course 6: dessert course", location: "Fullerton Hotel — Ballroom",
    poc: [], deadline: null, tasks: [] },
  { section: "Dinner", track: "setup", side: "everyone", start: "21:30", end: "22:15",
    title: "Band set 2", location: "Fullerton Hotel — Ballroom",
    poc: ["julian"], deadline: null,
    tasks: ["Musical Touch performs the second live set."] },
  { section: "Dinner", track: "program", side: "everyone", start: "21:30", end: "22:25",
    title: "Table photo taking", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "pauline"], deadline: null,
    tasks: [
      "Coordinate with photographers on photo taking with guests after the second march-in.",
      "Roughly two to three minutes per table.",
    ] },
  { section: "Dinner", track: "program", side: "everyone", start: "22:25", end: "22:35",
    title: "Farewell & final group photos", location: "Fullerton Hotel — Ballroom",
    poc: ["bride", "groom", "parents", "pauline"], deadline: null,
    tasks: [
      "Bid guests farewell and take final group photos.",
      "Coordinate remaining family and bridal party photos.",
    ] },
  { section: "Dinner", track: "setup", side: "everyone", start: "22:35", end: "23:00",
    title: "Vendor teardown", location: "Fullerton Hotel — Ballroom & Reception",
    poc: ["xinli", "mingfeng", "ryanjee", "yuntong", "alistair", "scarlet", "julian"], deadline: null,
    tasks: [
      "Photobooth, Victoria Wedding deco and Musical Touch teardown.",
      "Each segment's POC ensures teardown and brings remaining items into the bridal suite, or asks the banquet manager for disposal.",
    ] },
  { section: "Dinner", track: "setup", side: "everyone", start: "22:45", end: "23:00",
    title: "Clear ballroom items", location: "Fullerton Hotel — Ballroom",
    poc: ["bmgm"], deadline: null,
    tasks: [
      "Clear items from the ballroom and send them to the hotel room.",
      "Collect the reception decor, photo album, gown bags, shoes and personal items.",
    ] },
];
